name: game_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: 'none'

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  uuid: ^4.5.2
  core:
    path: ../core
  http: ^1.6.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
